version: '2'
services:
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=devcamp
    ports:
      - 5433:5433
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
    command: -p 5433