// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipper.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddShipperReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ImageURL             string   `protobuf:"bytes,2,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	MaxWeight            int32    `protobuf:"varint,4,opt,name=MaxWeight,proto3" json:"MaxWeight,omitempty"`
	CreatedBy            int32    `protobuf:"varint,5,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShipperReq) Reset()         { *m = AddShipperReq{} }
func (m *AddShipperReq) String() string { return proto.CompactTextString(m) }
func (*AddShipperReq) ProtoMessage()    {}
func (*AddShipperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{0}
}

func (m *AddShipperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShipperReq.Unmarshal(m, b)
}
func (m *AddShipperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShipperReq.Marshal(b, m, deterministic)
}
func (m *AddShipperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShipperReq.Merge(m, src)
}
func (m *AddShipperReq) XXX_Size() int {
	return xxx_messageInfo_AddShipperReq.Size(m)
}
func (m *AddShipperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShipperReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddShipperReq proto.InternalMessageInfo

func (m *AddShipperReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddShipperReq) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *AddShipperReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddShipperReq) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *AddShipperReq) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type AddShipperResp struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShipperResp) Reset()         { *m = AddShipperResp{} }
func (m *AddShipperResp) String() string { return proto.CompactTextString(m) }
func (*AddShipperResp) ProtoMessage()    {}
func (*AddShipperResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{1}
}

func (m *AddShipperResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShipperResp.Unmarshal(m, b)
}
func (m *AddShipperResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShipperResp.Marshal(b, m, deterministic)
}
func (m *AddShipperResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShipperResp.Merge(m, src)
}
func (m *AddShipperResp) XXX_Size() int {
	return xxx_messageInfo_AddShipperResp.Size(m)
}
func (m *AddShipperResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShipperResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddShipperResp proto.InternalMessageInfo

func (m *AddShipperResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AddShipperResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetShipperReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipperReq) Reset()         { *m = GetShipperReq{} }
func (m *GetShipperReq) String() string { return proto.CompactTextString(m) }
func (*GetShipperReq) ProtoMessage()    {}
func (*GetShipperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{2}
}

func (m *GetShipperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipperReq.Unmarshal(m, b)
}
func (m *GetShipperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipperReq.Marshal(b, m, deterministic)
}
func (m *GetShipperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipperReq.Merge(m, src)
}
func (m *GetShipperReq) XXX_Size() int {
	return xxx_messageInfo_GetShipperReq.Size(m)
}
func (m *GetShipperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipperReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipperReq proto.InternalMessageInfo

func (m *GetShipperReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetShipperResp struct {
	Data                 []*ShipperData `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetShipperResp) Reset()         { *m = GetShipperResp{} }
func (m *GetShipperResp) String() string { return proto.CompactTextString(m) }
func (*GetShipperResp) ProtoMessage()    {}
func (*GetShipperResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{3}
}

func (m *GetShipperResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipperResp.Unmarshal(m, b)
}
func (m *GetShipperResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipperResp.Marshal(b, m, deterministic)
}
func (m *GetShipperResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipperResp.Merge(m, src)
}
func (m *GetShipperResp) XXX_Size() int {
	return xxx_messageInfo_GetShipperResp.Size(m)
}
func (m *GetShipperResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipperResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipperResp proto.InternalMessageInfo

func (m *GetShipperResp) GetData() []*ShipperData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetShipperResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ShipperData struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	MaxWeight            int32    `protobuf:"varint,5,opt,name=MaxWeight,proto3" json:"MaxWeight,omitempty"`
	CreatedAt            int32    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy            int32    `protobuf:"varint,7,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt            int32    `protobuf:"varint,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy            int32    `protobuf:"varint,9,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipperData) Reset()         { *m = ShipperData{} }
func (m *ShipperData) String() string { return proto.CompactTextString(m) }
func (*ShipperData) ProtoMessage()    {}
func (*ShipperData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{4}
}

func (m *ShipperData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipperData.Unmarshal(m, b)
}
func (m *ShipperData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipperData.Marshal(b, m, deterministic)
}
func (m *ShipperData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipperData.Merge(m, src)
}
func (m *ShipperData) XXX_Size() int {
	return xxx_messageInfo_ShipperData.Size(m)
}
func (m *ShipperData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipperData.DiscardUnknown(m)
}

var xxx_messageInfo_ShipperData proto.InternalMessageInfo

func (m *ShipperData) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShipperData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipperData) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *ShipperData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ShipperData) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *ShipperData) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ShipperData) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *ShipperData) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ShipperData) GetUpdatedBy() int32 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

type DeleteShipperReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShipperReq) Reset()         { *m = DeleteShipperReq{} }
func (m *DeleteShipperReq) String() string { return proto.CompactTextString(m) }
func (*DeleteShipperReq) ProtoMessage()    {}
func (*DeleteShipperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{5}
}

func (m *DeleteShipperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShipperReq.Unmarshal(m, b)
}
func (m *DeleteShipperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShipperReq.Marshal(b, m, deterministic)
}
func (m *DeleteShipperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShipperReq.Merge(m, src)
}
func (m *DeleteShipperReq) XXX_Size() int {
	return xxx_messageInfo_DeleteShipperReq.Size(m)
}
func (m *DeleteShipperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShipperReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShipperReq proto.InternalMessageInfo

func (m *DeleteShipperReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteShipperResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShipperResp) Reset()         { *m = DeleteShipperResp{} }
func (m *DeleteShipperResp) String() string { return proto.CompactTextString(m) }
func (*DeleteShipperResp) ProtoMessage()    {}
func (*DeleteShipperResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2a14d76411df457, []int{6}
}

func (m *DeleteShipperResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShipperResp.Unmarshal(m, b)
}
func (m *DeleteShipperResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShipperResp.Marshal(b, m, deterministic)
}
func (m *DeleteShipperResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShipperResp.Merge(m, src)
}
func (m *DeleteShipperResp) XXX_Size() int {
	return xxx_messageInfo_DeleteShipperResp.Size(m)
}
func (m *DeleteShipperResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShipperResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShipperResp proto.InternalMessageInfo

func (m *DeleteShipperResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddShipperReq)(nil), "product.AddShipperReq")
	proto.RegisterType((*AddShipperResp)(nil), "product.AddShipperResp")
	proto.RegisterType((*GetShipperReq)(nil), "product.GetShipperReq")
	proto.RegisterType((*GetShipperResp)(nil), "product.GetShipperResp")
	proto.RegisterType((*ShipperData)(nil), "product.ShipperData")
	proto.RegisterType((*DeleteShipperReq)(nil), "product.DeleteShipperReq")
	proto.RegisterType((*DeleteShipperResp)(nil), "product.DeleteShipperResp")
}

func init() { proto.RegisterFile("shipper.proto", fileDescriptor_b2a14d76411df457) }

var fileDescriptor_b2a14d76411df457 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x37, 0x69, 0xbb, 0xd9, 0x4e, 0x95, 0x0a, 0x2c, 0x04, 0x26, 0x42, 0x22, 0xf2, 0x85,
	0x70, 0x20, 0x91, 0x96, 0x1b, 0x17, 0xd4, 0x10, 0x09, 0x2a, 0xb1, 0x1c, 0x02, 0x2b, 0x24, 0x6e,
	0xa6, 0x19, 0xb5, 0x91, 0xb6, 0x1b, 0x63, 0x1b, 0x44, 0x1f, 0x80, 0xc7, 0xe0, 0xb1, 0x78, 0x1f,
	0x14, 0x27, 0x4d, 0x9d, 0x40, 0xbb, 0x27, 0xc7, 0xf3, 0xff, 0x9e, 0x8c, 0xbf, 0x19, 0x83, 0xaf,
	0x36, 0xa5, 0x10, 0x28, 0x63, 0x21, 0x2b, 0x5d, 0x11, 0x4f, 0xc8, 0xaa, 0xf8, 0xbe, 0xd2, 0xec,
	0xb7, 0x03, 0xfe, 0xa2, 0x28, 0x3e, 0x36, 0x6a, 0x8e, 0xdf, 0x08, 0x81, 0xf1, 0x07, 0xbe, 0x45,
	0xea, 0x84, 0x4e, 0x34, 0xcd, 0xcd, 0x37, 0x09, 0xe0, 0x62, 0xb9, 0xe5, 0x6b, 0xbc, 0xce, 0xdf,
	0x53, 0xd7, 0xc4, 0xbb, 0x3d, 0x09, 0x61, 0x96, 0xa1, 0x5a, 0xc9, 0x52, 0xe8, 0xb2, 0xba, 0xa5,
	0x23, 0x23, 0xdb, 0x21, 0xf2, 0x04, 0xa6, 0x57, 0xfc, 0xe7, 0x67, 0x2c, 0xd7, 0x1b, 0x4d, 0xc7,
	0xa1, 0x13, 0x4d, 0xf2, 0x43, 0xa0, 0x56, 0xdf, 0x48, 0xe4, 0x1a, 0x8b, 0x74, 0x47, 0x27, 0x8d,
	0xda, 0x05, 0xd8, 0x2b, 0x98, 0xdb, 0xe5, 0x29, 0x41, 0xe6, 0xe0, 0x2e, 0x33, 0x53, 0xdd, 0x28,
	0x77, 0x97, 0x19, 0xa1, 0xe0, 0x5d, 0xa1, 0x52, 0x7c, 0x8d, 0x6d, 0x69, 0xfb, 0x2d, 0x7b, 0x0a,
	0xfe, 0x5b, 0xd4, 0xd6, 0xd5, 0x06, 0x47, 0xd9, 0x27, 0x98, 0xdb, 0x06, 0x25, 0x48, 0x04, 0xe3,
	0x8c, 0x6b, 0x4e, 0x9d, 0x70, 0x14, 0xcd, 0x2e, 0x1f, 0xc4, 0x2d, 0xa6, 0xb8, 0xf5, 0xd4, 0x5a,
	0x6e, 0x1c, 0x27, 0x7e, 0xfb, 0xcb, 0x85, 0x99, 0xe5, 0xff, 0xa7, 0xe0, 0x3d, 0x60, 0xf7, 0x08,
	0xe0, 0xd1, 0x69, 0xc0, 0xe3, 0x3b, 0x00, 0x4f, 0x8e, 0x03, 0x5e, 0x68, 0x7a, 0xde, 0x03, 0xbc,
	0x18, 0xe0, 0xf7, 0x06, 0xf8, 0x6b, 0xf5, 0x5a, 0x14, 0xed, 0xd9, 0x8b, 0x46, 0xed, 0x02, 0x96,
	0x9a, 0xee, 0xe8, 0xb4, 0xa7, 0xa6, 0x3b, 0xc6, 0xe0, 0x5e, 0x86, 0x37, 0xa8, 0xf1, 0x44, 0x07,
	0x5e, 0xc0, 0xfd, 0x81, 0x47, 0x89, 0x1a, 0xed, 0xb6, 0x45, 0xdb, 0x0c, 0xe1, 0x7e, 0x7b, 0xf9,
	0xc7, 0x01, 0xaf, 0x75, 0x92, 0xd7, 0x00, 0x87, 0xc9, 0x20, 0x0f, 0xbb, 0x56, 0xf5, 0xa6, 0x39,
	0x78, 0xf4, 0xdf, 0xb8, 0x12, 0xec, 0xac, 0x4e, 0x70, 0xe8, 0xbe, 0x95, 0xa0, 0x37, 0x33, 0x56,
	0x82, 0xfe, 0xa8, 0xb0, 0x33, 0xf2, 0x0e, 0xfc, 0x5e, 0xf1, 0xe4, 0x71, 0xe7, 0x1d, 0x5e, 0x3c,
	0x08, 0x8e, 0x49, 0x75, 0xa6, 0xf4, 0xf9, 0x97, 0x67, 0x71, 0xa2, 0x50, 0xfe, 0x28, 0x57, 0x68,
	0x56, 0x94, 0xc9, 0x86, 0xdf, 0x16, 0x37, 0x28, 0x55, 0xd2, 0xbe, 0xdc, 0xc4, 0xbc, 0xdc, 0xaf,
	0xe7, 0x66, 0x79, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x42, 0x61, 0xb8, 0x98, 0xd1, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShipperClient is the client API for Shipper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShipperClient interface {
	AddShipper(ctx context.Context, in *AddShipperReq, opts ...grpc.CallOption) (*AddShipperResp, error)
	GetShipper(ctx context.Context, in *GetShipperReq, opts ...grpc.CallOption) (*GetShipperResp, error)
	DeleteShipper(ctx context.Context, in *DeleteShipperReq, opts ...grpc.CallOption) (*DeleteShipperResp, error)
}

type shipperClient struct {
	cc *grpc.ClientConn
}

func NewShipperClient(cc *grpc.ClientConn) ShipperClient {
	return &shipperClient{cc}
}

func (c *shipperClient) AddShipper(ctx context.Context, in *AddShipperReq, opts ...grpc.CallOption) (*AddShipperResp, error) {
	out := new(AddShipperResp)
	err := c.cc.Invoke(ctx, "/product.Shipper/AddShipper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipperClient) GetShipper(ctx context.Context, in *GetShipperReq, opts ...grpc.CallOption) (*GetShipperResp, error) {
	out := new(GetShipperResp)
	err := c.cc.Invoke(ctx, "/product.Shipper/GetShipper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipperClient) DeleteShipper(ctx context.Context, in *DeleteShipperReq, opts ...grpc.CallOption) (*DeleteShipperResp, error) {
	out := new(DeleteShipperResp)
	err := c.cc.Invoke(ctx, "/product.Shipper/DeleteShipper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipperServer is the server API for Shipper service.
type ShipperServer interface {
	AddShipper(context.Context, *AddShipperReq) (*AddShipperResp, error)
	GetShipper(context.Context, *GetShipperReq) (*GetShipperResp, error)
	DeleteShipper(context.Context, *DeleteShipperReq) (*DeleteShipperResp, error)
}

func RegisterShipperServer(s *grpc.Server, srv ShipperServer) {
	s.RegisterService(&_Shipper_serviceDesc, srv)
}

func _Shipper_AddShipper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShipperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipperServer).AddShipper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Shipper/AddShipper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipperServer).AddShipper(ctx, req.(*AddShipperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shipper_GetShipper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipperServer).GetShipper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Shipper/GetShipper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipperServer).GetShipper(ctx, req.(*GetShipperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shipper_DeleteShipper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShipperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipperServer).DeleteShipper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.Shipper/DeleteShipper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipperServer).DeleteShipper(ctx, req.(*DeleteShipperReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shipper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.Shipper",
	HandlerType: (*ShipperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddShipper",
			Handler:    _Shipper_AddShipper_Handler,
		},
		{
			MethodName: "GetShipper",
			Handler:    _Shipper_GetShipper_Handler,
		},
		{
			MethodName: "DeleteShipper",
			Handler:    _Shipper_DeleteShipper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipper.proto",
}
